version="2.0"
watch_list=["docs/src/*.md"]
hooks=["shebang", "quarto_attributes", "brei"]

[markers]
open="^(?P<indent>\\s*)```(?P<properties>.*)$"
close="^(?P<indent>\\s*)```\\s*$"

# Get rid of warnings about unknown language
[[languages]]
name="JuliaREPL"
identifiers=["julia-repl"]
comment={open="#"}
